version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: urlshortcontainer
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app

    command: npm start